# Generated by Django 4.0.3 on 2022-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000, null=True)),
                ('author', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img_uri', models.CharField(max_length=999999)),
                ('category', models.CharField(choices=[('Abs', 'Abs'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('butt-hips', 'butt-hips'), ('full-body-integrated', 'full-body-integrated'), ('legs-calves-and-shins', 'legs-calves-and-shins'), ('legs-thighs', 'legs-thighs'), ('Neck', 'Neck')], max_length=128)),
                ('community_contrib', models.BooleanField(default=False)),
            ],
        ),
    ]
